from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1152, 858)
        MainWindow.setStyleSheet("font: 75 10pt \"Comic Sans MS\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.centralwidget.setFont(font)
        self.centralwidget.setStyleSheet("font: 75 10pt \"Comic Sans MS\";")
        self.centralwidget.setObjectName("centralwidget")
        self.drugcode = QtWidgets.QLabel(self.centralwidget)
        self.drugcode.setGeometry(QtCore.QRect(320, 60, 81, 31))
        self.drugcode.setObjectName("drugcode")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(390, 60, 161, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(390, 110, 161, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.drugname = QtWidgets.QLabel(self.centralwidget)
        self.drugname.setGeometry(QtCore.QRect(320, 110, 81, 31))
        self.drugname.setObjectName("drugname")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(390, 160, 161, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.expirationdate = QtWidgets.QLabel(self.centralwidget)
        self.expirationdate.setGeometry(QtCore.QRect(290, 160, 101, 31))
        self.expirationdate.setObjectName("expirationdate")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(390, 210, 161, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.barcodeno = QtWidgets.QLabel(self.centralwidget)
        self.barcodeno.setGeometry(QtCore.QRect(310, 210, 81, 31))
        self.barcodeno.setObjectName("barcodeno")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(390, 250, 161, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.price = QtWidgets.QLabel(self.centralwidget)
        self.price.setGeometry(QtCore.QRect(350, 250, 41, 31))
        self.price.setObjectName("price")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(390, 300, 161, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.piece = QtWidgets.QLabel(self.centralwidget)
        self.piece.setGeometry(QtCore.QRect(350, 300, 41, 31))
        self.piece.setObjectName("piece")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(390, 350, 161, 31))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.producingcompany = QtWidgets.QLabel(self.centralwidget)
        self.producingcompany.setGeometry(QtCore.QRect(270, 350, 121, 31))
        self.producingcompany.setObjectName("producingcompany")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(390, 400, 161, 31))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.usage = QtWidgets.QLabel(self.centralwidget)
        self.usage.setGeometry(QtCore.QRect(340, 400, 81, 31))
        self.usage.setObjectName("usage")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(650, 60, 75, 50))
        self.pushButton.setStyleSheet("border-image: url(icon/search.png);\n"
"background-color: rgb(255, 114, 116);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(650, 130, 75, 50))
        self.pushButton_2.setStyleSheet("border-image: url(icon/delete.png);")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(650, 200, 75, 50))
        self.pushButton_3.setStyleSheet("border-image: url(icon/update.png);")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(650, 270, 75, 50))
        self.pushButton_4.setStyleSheet("border-image: url(icon/insert.png);")
        self.pushButton_4.setText("")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(650, 340, 75, 50))
        self.pushButton_5.setStyleSheet("border-image: url(icon/clear.png);")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 560, 1141, 192))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(140)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(80)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(50)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setMinimumSectionSize(40)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1152, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.drugcode.setBuddy(self.lineEdit)
        self.drugname.setBuddy(self.lineEdit_2)
        self.expirationdate.setBuddy(self.lineEdit_3)
        self.barcodeno.setBuddy(self.lineEdit_4)
        self.price.setBuddy(self.lineEdit_5)
        self.piece.setBuddy(self.lineEdit_6)
        self.producingcompany.setBuddy(self.lineEdit_7)
        self.usage.setBuddy(self.lineEdit_8)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.drugcode.setText(_translate("MainWindow", "Drug Code:"))
        self.drugname.setText(_translate("MainWindow", "Drug Name:"))
        self.expirationdate.setText(_translate("MainWindow", "Expiration Date:"))
        self.barcodeno.setText(_translate("MainWindow", "Barcode No:"))
        self.price.setText(_translate("MainWindow", "Price:"))
        self.piece.setText(_translate("MainWindow", "Piece:"))
        self.producingcompany.setText(_translate("MainWindow", "Producing Company:"))
        self.usage.setText(_translate("MainWindow", "Usage:"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Drug Code"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Drug Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Expiration Date"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Barcode No"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Price"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Piece"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Producing Company"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Usage"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())